title: "Alex Statham"
email: alex.statham1998@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A compilation of the Education and achievements of Alex Statham.
baseurl: "/"
url: "https://Astatham98.github.io"
twitter_username: Alexstatham98
github_username:  Astatham98

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
